name: flutter_new_project_template_with_riverpod
description: "Flutter template to help devs start building apps faster than ever. It includes general usecases for project"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0



dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  rename_app: ^1.6.1
  flutter_scripts: ^0.0.3
  change_app_package_name: ^1.4.0
  lottie: ^3.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:

    - assets/images/
    - assets/animations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo/app_logo.png"


scripts:
  generate_icons: flutter pub run flutter_launcher_icons
  generate_files: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner build watch --delete-conflicting-outputs
  buildApk: flutter clean && flutter build apk
  buildAbb: flutter clean && flutter build appbundle
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
