name: fedman_admin_app
description: "Flutter template to help devs start building apps faster than ever. It includes general usecases for project"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1



dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  rename_app: ^1.6.1
  flutter_scripts:
    git: https://github.com/mehroze-zaidi/flutter_scripts.git
  change_app_package_name: ^1.5.0
  lottie: ^3.0.0
  flutter_screenutil: ^5.9.3
  go_router: ^16.2.4
  easy_localization: ^3.0.8
  flutter_svg: ^2.2.1
  fluttertoast: ^9.0.0
  dio: ^5.9.0
  logger: ^2.6.1
  get_it: ^8.2.0
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.0
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  intl_phone_field: ^3.2.0
  cached_network_image: ^3.4.1
  flutter_dropzone: ^4.2.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  freezed: ^3.2.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  assets:

    - assets/images/
    - assets/animations/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo/app_logo.png"


scripts:
  #To generate native splash screen: dart run flutter_native_splash:create --path=path/to/my/file.yaml
  #To change package name: dart run change_app_package_name:main com.new.package.name
  #To rename app name:  dart run rename_app:main all="My App Name"
  generate_icons: flutter pub run flutter_launcher_icons
  generate_files: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner build watch --delete-conflicting-outputs
  buildApk: flutter clean && flutter build apk
  buildAbb: flutter clean && flutter build appbundle
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
